### ISSUE TITLE
Why the need to install Miniconda?

### ISSUE THREAD

**Issue by HamletFr** [symengine/SymEngine.jl#112]
I have a anaconda version installed on my PC and in Julia the environment variable set
ENV["PYTHON"]="/anaconda3/bin/python"
and the Conda Package installed and build with this variable.

Why does the SymEngine then need to install Miniconda on my PC? Does it not work with Python 3?

**Comment by isuruf** [comment]
It's `Conda.jl` that does this. You can do `export CONDA_JL_HOME=/anaconda3/bin/python` and then rebuild `Conda.jl`.

**Comment by HamletFr** [comment]
Sorry, but I am not that used to it: where do I need to run
`export CONDA_JL_HOME=/anaconda3/bin/python`
Inside Julia?

**Comment by isuruf** [comment]
Outside. Inside Julia, you can do `ENV["CONDA_JL_HOME"]="/anaconda3/"` and rebuild `Conda.jl`

**Comment by HamletFr** [comment]
Works perfectly ... Thanks!

**Comment by isuruf** [comment]
Great.
