### ISSUE TITLE
v0.7 upgrading

### ISSUE THREAD

**Issue by ChrisRackauckas** [symengine/SymEngine.jl#115]
Julia's v0.7 is going to alpha sooner rather than later, so I was wondering if SymEngine could get its upgrade. Right now it segfaults. `using ParameterizedFunctions` just segfaults and it seems to be SymEngine related, plus SymEngine.jl's tests fail.

**Comment by isuruf** [comment]
Fixed in https://github.com/symengine/SymEngine.jl/pull/118
