### ISSUE TITLE
Conversion of matrix to expressions

### ISSUE THREAD

**Issue by ChrisRackauckas** [symengine/SymEngine.jl#122]
This doesn't work so well. https://github.com/symengine/SymEngine.jl/blob/9c393c39a80f972fd876b833b8fdee918df3980e/src/subs.jl#L76-L87 converts it to the Python form. 

```julia
symjac_ex = :([[1 0]; [d * t ^ 2 * y -1c + d * t ^ 2 * x]])
```

Broadcasting doesn't guarantee and expression so you get something odd

```julia
symjac_ex = Any[1 0; :(d * t ^ 2 * y) :(-1c + d * t ^ 2 * x)]
```

It should be an array of expressions, but `1` and `0` are integer literals and not expressions here.

**Comment by isuruf** [comment]
What's your expected output?

**Comment by ChrisRackauckas** [comment]
An array of `Expr` instead of `Any`, with expressions instead of integers. I.e. `:(1)`, etc.

**Comment by isuruf** [comment]
How do you make an Expr out of integers? `:(1)` gives an integer.

**Comment by ChrisRackauckas** [comment]
No idea. I didn't know it did that.

**Comment by ChrisRackauckas** [comment]
```julia
julia> :(1)
1

julia> :1
1

julia> :(1*1)
:(1 * 1)
```

that's the only workaround I can think of.

**Comment by isuruf** [comment]
Looks good to me. Can you send a PR?

**Comment by ChrisRackauckas** [comment]
Yeah I will but ain't promising it soon.

**Comment by isuruf** [comment]
Ah, didnt realize Symbol was not an Expr
