### ISSUE TITLE
Writing to file

### ISSUE THREAD

**Issue by AlexJohnson1995** [symengine/SymEngine.jl#127]
Is it possible to write the results of differentiation to file and how, if yes? When i try to write it, i receive the following error: `MethodError: no method matching write(::IOStream, ::SymEngine.Basic)`

**Comment by ChrisRackauckas** [comment]
Convert to an expression first?

**Comment by AlexJohnson1995** [comment]
@ChrisRackauckas , i tried, and it worked. Thank you!
