### ISSUE TITLE
assertion failure in SymEngine build

### ISSUE THREAD

**Issue by JeffBezanson** [symengine/SymEngine.jl#132]
With julia 0.7.0-rc1.24 on linux x86-64:
```
(v0.7) pkg> build SymEngine
  Building SymEngine → `~/.julia/packages/SymEngine/eA6lW/deps/build.log`
┌ Error: Error building `SymEngine`: 
│ ┌ Warning: __precompile__() is now the default
│ │   caller = __precompile__() at loading.jl:777
│ └ @ Base ./loading.jl:777
│ WARNING: Base.UVError is deprecated, use IOError instead.
│   likely near string:26
│ WARNING: Base.UVError is deprecated, use IOError instead.
│   likely near string:26
│ in safe_isfile at /home/jeff/.julia/packages/BinaryProvider/mWAR/src/Prefix.jl
│ Inconsistency detected by ld.so: dl-close.c: 762: _dl_close: Assertion `map->l_init_called' failed!
└ @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v0.7/Pkg/src/Operations.jl:1061
```

**Comment by isuruf** [comment]
This might be because of libgmp that we provide using BinaryProvider, but julia itself depends on libgmp and the `satisfied` call in BinaryProvider script loads `libgmp` and if successful, closes it.

**Comment by isuruf** [comment]
How can I reproduce this? Is there a docker image I can use?

**Comment by JeffBezanson** [comment]
I don't have one, sorry. Fortunately I've been able to make progress on the julia issue without this.

**Comment by isuruf** [comment]
Can't reproduce. We've had several releases since then. If you run into this issue again, please re-open this issue. (Or create a new one)
