### ISSUE TITLE
Error when using SymEngine inside a module

### ISSUE THREAD

**Issue by SabbahMohammed** [symengine/SymEngine.jl#143]
Consider the following module
```
module MyDispersion
export lbeta2, wbeta2, beta0
using SymEngine
c = 3e8
b_1 = 39209.95*10^-8.0
b_2 = 18806.48*10^-8.0
c_1 = 1146.24*10^-6.0*10^-12.0/(4*pi^2*c^2)
c_2 = 13.476*10^-3.0*10^-12.0/(4*pi^2*c^2)
p_0 = 1
Tk_0 = 273
u = 2.40482555769577 
x = symbols(:x)
function beta0(x::Basic, p::Float64, Tk::Float64, a::Float64)
    return x/c + 0.5*x*p*Tk_0*(b_1/(1-c_1*x^2) + b_2/(1-c_2*x^2))/(c*p_0*Tk) - .5*u^2*c/(a^2*x)
end
function beta1(x::Basic, p::Float64, Tk::Float64, a::Float64)
    return diff(beta0(x, p, Tk, a), x)
end
function beta2(x::Basic, p::Float64, Tk::Float64, a::Float64)
    return diff(beta1(x, p, Tk, a), x)
end
function wbeta2(ω::Float64, p::Float64, Tk::Float64, a::Float64)
    y = beta2(x, p, Tk, a)
    return Float64(subs(y, x=>ω))
end

function lbeta2(λ::Float64, p::Float64, Tk::Float64, a::Float64)
    ω = (2pi*c)/λ
    y = beta2(x, p, Tk, a)
    return Float64(subs(y, (x,ω)))
end
end
```

When I use it like follow

```
using MyDispersion

using Plots
gr()

xx(ω) = wbeta2(ω, 1.0, 300.0, 13e-6)
plot(xx, 1.5e15:0.2e15:9.5e15, xticks = (1.5e15:2e15:9.5e15), yticks = (-3e-27:1e-27:3e-27), xlims = (1.5e15, 9.5e15), ylims = (-3e-27,3e-27))
```

I get the following error

`Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x2f1ae6eb -- _ZN9SymEngine3mulERKNS_3RCPIKNS_5BasicEEES5_ at C:\Users\Mohammed Sabbah\.julia\packages\SymEngine\sh7Yz\deps\symengine-0.3\bin\libsymengine.dll (unknown line)
in expression starting at no file:0
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x2f1ae6eb -- _ZN9SymEngine3mulERKNS_3RCPIKNS_5BasicEEES5_ at C:\Users\Mohammed Sabbah\.julia\packages\SymEngine\sh7Yz\deps\symengine-0.3\bin\libsymengine.dll (unknown line)
in expression starting at no file:0
_ZN9SymEngine3mulERKNS_3RCPIKNS_5BasicEEES5_ at C:\Users\Mohammed Sabbah\.julia\packages\SymEngine\sh7Yz\deps\symengine-0.3\bin\libsymengine.dll (unknown line)
_ZN9SymEngine3divERKNS_3RCPIKNS_5BasicEEES5_ at C:\Users\Mohammed Sabbah\.julia\packages\SymEngine\sh7Yz\deps\symengine-0.3\bin\libsymengine.dll (unknown line)
basic_div at C:\Users\Mohammed Sabbah\.julia\packages\SymEngine\sh7Yz\deps\symengine-0.3\bin\libsymengine.dll (unknown line)
/ at C:\Users\Mohammed Sabbah\.julia\packages\SymEngine\sh7Yz\src\mathops.jl:16
/ at .\promotion.jl:316
unknown function (ip: 00000000155FD50F)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
beta0 at C:\Users\Mohammed Sabbah\OneDrive - Heriot-Watt University\programming\julia\MyDispersion\MyDispersion.jl:51
beta1 at C:\Users\Mohammed Sabbah\OneDrive - Heriot-Watt University\programming\julia\MyDispersion\MyDispersion.jl:55
beta2 at C:\Users\Mohammed Sabbah\OneDrive - Heriot-Watt University\programming\julia\MyDispersion\MyDispersion.jl:59
wbeta2 at C:\Users\Mohammed Sabbah\OneDrive - Heriot-Watt University\programming\julia\MyDispersion\MyDispersion.jl:63
xx at C:\Users\Mohammed Sabbah\OneDrive - Heriot-Watt University\programming\julia\test.jl:57
unknown function (ip: 00000000155FBE7B)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:428
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:682
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:799
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000000EF6658F)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:787
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:622
eval at .\boot.jl:319 [inlined]
repleval at C:\Users\Mohammed Sabbah\.julia\packages\Atom\WSz3k\src\repl.jl:130
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
#160 at C:\Users\Mohammed Sabbah\.julia\packages\Atom\WSz3k\src\repl.jl:149
with_logstate at .\logging.jl:397
with_logger at .\logging.jl:493 [inlined]
evalrepl at C:\Users\Mohammed Sabbah\.julia\packages\Atom\WSz3k\src\repl.jl:140
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:428
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:682
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:799
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000000F2090EF)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:787
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:622
eval at .\boot.jl:319
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
eval_user_input at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:85
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:117 [inlined]
#28 at .\task.jl:259
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1536 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:268
Allocations: 40912887 (Pool: 40906834; Big: 6053); GC: 89
`
While if I used the code without putting it in a module, I dont get any error.

**Comment by isuruf** [comment]
Don't store `SymEngine::Basic` in a module that is precompiled. Either convert `SymEngine::Basic` to `Expr` or add a `__init__` method that initializes `x`.
This issue is because C pointers are freed after each session.

**Comment by SabbahMohammed** [comment]
@isuruf  Thanks, the __init__ method solved the problem
