### ISSUE TITLE
Build Error in Ubuntu 16.04

### ISSUE THREAD

**Issue by ylzhang16** [symengine/SymEngine.jl#151]
Meet error when building SymEngine in Ubuntu 16.04.  

Error: Error building `SymEngine`:
│ ERROR: LoadError: LoadError: Could not unpack /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/symengine-0.3/downloads/SymEngine.v0.3.0.x86_64-linux-gnu.tar.gz into /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/symengine-0.3
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #unpack#98(::Bool, ::Function, ::String, ::String) at /home/julia/worker/juliapro-release-centos7-0_6/build/tmp_julia/share/julia/stdlib/v1.0/BinaryProvider/src/PlatformEngines.jl:607
│  [3] #unpack at ./none:0 [inlined]
│  [4] macro expansion at ./logging.jl:322 [inlined]
│  [5] #install#115(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /home/julia/worker/juliapro-release-centos7-0_6/build/tmp_julia/share/julia/stdlib/v1.0/BinaryProvider/src/Prefix.jl:358
│  [6] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│  [7] top-level scope at string:36
│  [8] include_string(::Module, ::String, ::String) at ./loading.jl:1005
│  [9] include_string(::Module, ::String) at ./loading.jl:1009
│  [10] top-level scope at /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/build.jl:31
│  [11] include at ./boot.jl:317 [inlined]
│  [12] include_relative(::Module, ::String) at ./loading.jl:1041
│  [13] include(::Module, ::String) at ./sysimg.jl:29
│  [14] include(::String) at ./client.jl:388
│  [15] top-level scope at none:0
│ in expression starting at string:32
│ in expression starting at /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/build.jl:21
│ tar: ./share: Cannot unlink: Directory not empty
│ tar: ./share/doc: Cannot unlink: Directory not empty
│ tar: ./include: Cannot unlink: Directory not empty
│ tar: ./include/symengine: Cannot unlink: Directory not empty
│ tar: ./include/symengine/polys: Cannot unlink: Directory not empty
│ tar: ./manifests: Cannot unlink: Directory not empty
│ tar: ./logs: Cannot unlink: Directory not empty
│ tar: ./lib: Cannot unlink: Directory not empty
│ tar: ./lib/cmake: Cannot unlink: Directory not empty
│ tar: ./lib/cmake/symengine: Cannot unlink: Directory not empty
│ tar: Exiting with failure status due to previous errors
└ @ Pkg.Operations /home/julia/worker/juliapro-release-centos7-0_6/build/tmp_julia/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1101
  Building RandomNumbers ───→ `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/RandomNumbers/t1NfT/deps/build.log`
  Building Arpack ──────────→ `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/Arpack/WP3ru/deps/build.log`
  Building Rmath ───────────→ `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/Rmath/Py9gH/deps/build.log`

julia> Pkg.add("Conda")
 Resolving package versions...
 Installed Conda ────────── v1.0.2
 Installed VersionParsing ─ v1.1.3
  Updating `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/environments/JuliaPro_v1.0.1.1/Project.toml`
  [8f4d0f93] + Conda v1.0.2
  Updating `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/environments/JuliaPro_v1.0.1.1/Manifest.toml`
  [8f4d0f93] + Conda v1.0.2
  [81def892] + VersionParsing v1.1.3
  Building Conda → `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/Conda/hsaaN/deps/build.log`

julia> Pkg.build("DifferentialEquations")
  Building SpecialFunctions → `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SpecialFunctions/KvXoO/deps/build.log`
  Building DiffEqBase ──────→ `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/DiffEqBase/ujEgN/deps/build.log`
  Building RandomNumbers ───→ `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/RandomNumbers/t1NfT/deps/build.log`
  Building Arpack ──────────→ `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/Arpack/WP3ru/deps/build.log`
  Building Rmath ───────────→ `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/Rmath/Py9gH/deps/build.log`
  Building SymEngine ───────→ `~/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/build.log`
┌ Error: Error building `SymEngine`:
│ ERROR: LoadError: LoadError: Could not unpack /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/symengine-0.3/downloads/SymEngine.v0.3.0.x86_64-linux-gnu.tar.gz into /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/symengine-0.3
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #unpack#98(::Bool, ::Function, ::String, ::String) at /home/julia/worker/juliapro-release-centos7-0_6/build/tmp_julia/share/julia/stdlib/v1.0/BinaryProvider/src/PlatformEngines.jl:607
│  [3] #unpack at ./none:0 [inlined]
│  [4] macro expansion at ./logging.jl:322 [inlined]
│  [5] #install#115(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /home/julia/worker/juliapro-release-centos7-0_6/build/tmp_julia/share/julia/stdlib/v1.0/BinaryProvider/src/Prefix.jl:358
│  [6] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│  [7] top-level scope at string:36
│  [8] include_string(::Module, ::String, ::String) at ./loading.jl:1005
│  [9] include_string(::Module, ::String) at ./loading.jl:1009
│  [10] top-level scope at /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/build.jl:31
│  [11] include at ./boot.jl:317 [inlined]
│  [12] include_relative(::Module, ::String) at ./loading.jl:1041
│  [13] include(::Module, ::String) at ./sysimg.jl:29
│  [14] include(::String) at ./client.jl:388
│  [15] top-level scope at none:0
│ in expression starting at string:32
│ in expression starting at /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/build.jl:21
│ tar: ./share: Cannot unlink: Directory not empty
│ tar: ./share/doc: Cannot unlink: Directory not empty
│ tar: ./include: Cannot unlink: Directory not empty
│ tar: ./include/symengine: Cannot unlink: Directory not empty
│ tar: ./include/symengine/polys: Cannot unlink: Directory not empty
│ tar: ./manifests: Cannot unlink: Directory not empty
│ tar: ./logs: Cannot unlink: Directory not empty
│ tar: ./lib: Cannot unlink: Directory not empty
│ tar: ./lib/cmake: Cannot unlink: Directory not empty
│ tar: ./lib/cmake/symengine: Cannot unlink: Directory not empty
│ tar: Exiting with failure status due to previous errors

**Comment by isuruf** [comment]
Can you delete the folder `/home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/symengine-0.3` and try again?

**Comment by ylzhang16** [comment]
After reinstalling the whole JuliaPro, the question is still there. Other packages behave normally. Could I give the tar authority to solve this problem? Where could I add some commands such as `--overwrite` ?

**Comment by isuruf** [comment]
Can you try manually unpacking to the path given in the message?
`
│ ERROR: LoadError: LoadError: Could not unpack /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/symengine-0.3/downloads/SymEngine.v0.3.0.x86_64-linux-gnu.tar.gz into /home/bbnc/Julia/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/SymEngine/sh7Yz/deps/symengine-0.3
`

**Comment by ylzhang16** [comment]
Yes I tried and unpacking was successful, but when I start input `Pkg.build("SymEngine")`, the error info appears again. I check the build.jl of SymEngine and find the code 

```
for (url, hash) in dependencies
    tmp_file = joinpath(downloads_dir, "build_$hash.jl")
    download_verify(url, hash, tmp_file)
    contents = read(tmp_file, String)
    m = Module(:__anon__)
    Core.eval(m, quote
        using BinaryProvider
        function write_deps_file(path, products) end
        ARGS = [$prefix]
    end)
    Base.include_string(m, contents)
    products = Core.eval(m, :(products))
    append!(all_products, products)
end
```
So I think Julia would try to unpacking again, even I have unpacked.

**Comment by ylzhang16** [comment]
I have checked in another PC with Ubuntu 16.04 and the same error information appeared. Maybe a bug?

**Comment by rzhli** [comment]
same error with me
```
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```
and I wish an update version of Symengine

**Comment by isuruf** [comment]
I can't reproduce this, so I'll not be able to debug this. Sorry. If you can reproduce this in a Docker image, let me know and I'll debug this.

**Comment by rzhli** [comment]
error has gone since the new version released, thanks

**Comment by stroebel** [comment]
I have this problem using JuliaPro on 18.10 and I have no idea how to fix it

**Comment by stroebel** [comment]
I have tried that. I have also removed my entire .juliapro folder to have the entire distribution rebuild itself and I still have that problem. I have also tried directly pulling the git repository instead of installing it via the Pkg system for Julia.

**Comment by isuruf** [comment]
Can someone check https://github.com/symengine/SymEngine.jl/pull/153 ?
