### ISSUE TITLE
Obtaining the type of numeric coefficients

### ISSUE THREAD

**Issue by mforets** [symengine/SymEngine.jl#155]
Is there a utility in SymEngine to get the type of the numeric coefficients in an expression?

```julia
julia> using SymEngine

julia> ex_int = convert(Basic, :(x+2*y + 1))
1 + x + 2*y

julia> ex_float = convert(Basic, :(x+2.0*y + 1))
1 + x + 2.0*y

julia> typeof(ex_int) == typeof(ex_float)
true
```

The use case is to get the "constant coefficient" in an expression and use it later for dispatch; doing `K = subs(ex, [vi => zero(N) for vi in free_symbols(ex)]...)` needs to feed an appropriate `N`.

**Comment by isuruf** [comment]
I'm sorry, I don't understand the question. Can you explain a bit more?

**Comment by jverzani** [comment]
Maybe the method used to define N in this file is helpful https://github.com/symengine/SymEngine.jl/blob/master/src/numerics.jl ?

**Comment by mforets** [comment]
> I'm sorry, I don't understand the question. Can you explain a bit more?

Yes, thanks for you answers and sorry for my no-reply. In the same way as `y = 2x` is integer if `x` is an integer variable in Julia's REPL, I was expecting for `ex_int = convert(Basic, :(x+2*y + 1))` to carry the information that it's *an expression with integer coefficients*, and i was asking if this type information is available somewhere after the conversion to `Basic` or if it's lost (and Basic assumes that the coeffs are floats).

> Maybe the method used to define N in this file is helpful https://github.com/symengine/SymEngine.jl/blob/master/src/numerics.jl ?

I checked and it does go in the good direction,

```julia
julia> typeof(SymEngine.N(convert(Basic, :(2))))
Int64

julia> typeof(SymEngine.N(convert(Basic, :(2.0))))
Float64
```
But `SymEngine.N` does not directly apply to an expression such as `:(x+2*y + 1)` as [it shouldn't have free symbols](https://github.com/symengine/SymEngine.jl/blob/master/src/numerics.jl#L149). So one can certainly extend it by walking through the expression tree until all numerical coefficients have been considered. In sum, I think the bottom line that for the question "what is the (numeric) type of the coefficients in this symbolic expression?" is that there's not straightforward method to be used here.

I don't need this feature ATM (the adopted solution is to hardcode Float64's when i parse models, since this is anyways my use case) and from your answers and skimming through SymEngine's code, i have the impression that it doesn't quite make sense to have this method in the library, so i'm closing the issue.
