### ISSUE TITLE
Some problems with permissions

### ISSUE THREAD

**Issue by kirtsar** [symengine/SymEngine.jl#170]
```
(v1.1) pkg> build SymEngine
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`
  Building SymEngine ───────→ `~/.julia/packages/SymEngine/zSUGO/deps/build.log`
┌ Error: Error building `SymEngine`: 
│ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libgmp.so
│ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpfr.so
│ [ Info: Downloading https://github.com/isuruf/MPCBuilder/releases/download/v1.1.0-3/MPC.v1.1.0.x86_64-linux-gnu.tar.gz to /home/kir/.julia/packages/SymEngine/zSUGO/deps/downloads/mpc-1.1.0/downloads/MPC.v1.1.0.x86_64-linux-gnu.tar.gz...
│ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpc.so
│ [ Info: Downloading https://github.com/symengine/SymEngineBuilder/releases/download/v0.4.0-3/build_SymEngine.v0.4.0.jl to /home/kir/.julia/packages/SymEngine/zSUGO/deps/downloads/build_97348aaf042e3c81b938ac665a0c81e02b5f4e5125d76cedcd2fc3c9dcb182df.jl...
│ [ Info: Downloading https://github.com/symengine/SymEngineBuilder/releases/download/v0.4.0-3/SymEngine.v0.4.0.x86_64-linux-gnu.tar.gz to /home/kir/.julia/packages/SymEngine/zSUGO/deps/downloads/symengine-0.4.0/downloads/SymEngine.v0.4.0.x86_64-linux-gnu.tar.gz...
│ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.so
│ [ Info: Found a valid dl path libgmp.so while looking for libgmp
│ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libgmp.so matches our search criteria of libgmp
│ [ Info: Found a valid dl path libgmp.so while looking for libmpfr
│ [ Info: Found a valid dl path libgmp.so.10 while looking for libmpfr
│ [ Info: Found a valid dl path libgmp.so.10.3.2 while looking for libmpfr
│ [ Info: Found a valid dl path libgmpxx.so while looking for libmpfr
│ [ Info: Found a valid dl path libgmpxx.so.4 while looking for libmpfr
│ [ Info: Found a valid dl path libgmpxx.so.4.5.2 while looking for libmpfr
│ [ Info: Found a valid dl path libmpc.so while looking for libmpfr
│ [ Info: Found a valid dl path libmpc.so.3 while looking for libmpfr
│ [ Info: Found a valid dl path libmpc.so.3.1.0 while looking for libmpfr
│ [ Info: Found a valid dl path libmpfr.so while looking for libmpfr
│ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpfr.so matches our search criteria of libmpfr
│ [ Info: Found a valid dl path libgmp.so while looking for libmpc
│ [ Info: Found a valid dl path libgmp.so.10 while looking for libmpc
│ [ Info: Found a valid dl path libgmp.so.10.3.2 while looking for libmpc
│ [ Info: Found a valid dl path libgmpxx.so while looking for libmpc
│ [ Info: Found a valid dl path libgmpxx.so.4 while looking for libmpc
│ [ Info: Found a valid dl path libgmpxx.so.4.5.2 while looking for libmpc
│ [ Info: Found a valid dl path libmpc.so while looking for libmpc
│ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpc.so matches our search criteria of libmpc
│ [ Info: Found a valid dl path libgmp.so while looking for libsymengine
│ [ Info: Found a valid dl path libgmp.so.10 while looking for libsymengine
│ [ Info: Found a valid dl path libgmp.so.10.3.2 while looking for libsymengine
│ [ Info: Found a valid dl path libgmpxx.so while looking for libsymengine
│ [ Info: Found a valid dl path libgmpxx.so.4 while looking for libsymengine
│ [ Info: Found a valid dl path libgmpxx.so.4.5.2 while looking for libsymengine
│ [ Info: Found a valid dl path libmpc.so while looking for libsymengine
│ [ Info: Found a valid dl path libmpc.so.3 while looking for libsymengine
│ [ Info: Found a valid dl path libmpc.so.3.1.0 while looking for libsymengine
│ [ Info: Found a valid dl path libmpfr.so while looking for libsymengine
│ [ Info: Found a valid dl path libmpfr.so.6 while looking for libsymengine
│ [ Info: Found a valid dl path libmpfr.so.6.0.2 while looking for libsymengine
│ [ Info: Found a valid dl path libsymengine.so while looking for libsymengine
│ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.so matches our search criteria of libsymengine
│ ERROR: LoadError: SystemError: opening file "/home/kir/.julia/packages/SymEngine/zSUGO/deps/deps.jl": Permission denied
│ Stacktrace:
│  [1] #systemerror#43(::Nothing, ::Function, ::String, ::Bool) at ./error.jl:134
│  [2] systemerror at ./error.jl:134 [inlined]
│  [3] #open#309(::Nothing, ::Nothing, ::Nothing, ::Bool, ::Nothing, ::Function, ::String) at ./iostream.jl:289
│  [4] #open at ./none:0 [inlined]
│  [5] open(::String, ::String) at ./iostream.jl:345
│  [6] #open#310(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(BinaryProvider, Symbol("##154#158")){Bool,String,Array{LibraryProduct,1},getfield(BinaryProvider, Symbol("##153#157"))}, ::String, ::Vararg{String,N} where N) at ./iostream.jl:373
│  [7] open at ./iostream.jl:373 [inlined]
│  [8] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/kir/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:419
│  [9] write_deps_file(::String, ::Array{LibraryProduct,1}) at /home/kir/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:395
│  [10] top-level scope at none:0
│  [11] include at ./boot.jl:326 [inlined]
│  [12] include_relative(::Module, ::String) at ./loading.jl:1038
│  [13] include(::Module, ::String) at ./sysimg.jl:29
│  [14] include(::String) at ./client.jl:403
│  [15] top-level scope at none:0
│ in expression starting at /home/kir/.julia/packages/SymEngine/zSUGO/deps/build.jl:60
│ [10:31:02] #=#=#                                                              [10:31:03] ##O#- #                                                              [10:31:03] ##O=#  #                                                             [10:31:03] #=#=-#  #                                                            [10:31:03] -#O#- #   #                                                          [10:31:03] -=#=#   #   #                                                        [10:31:03] -=O#- #  #    #                                                      [10:31:03] -=O=#  #   #   #                                                     [10:31:04] ###############                                                      [10:31:05] ###############################################                      [10:31:05] ################################################                     [10:31:05] ######################################################################## 100,0%
│ [10:31:05] #=#=#                                                              [10:31:05] ##O#- #                                                              [10:31:05] ##O=#  #                                                             [10:31:05] #=#=-#  #                                                            [10:31:06] -#O#- #   #                                                          [10:31:06] -=#=#   #   #                                                        [10:31:06] ######################################################################## 100,0%
│ [10:31:06] #=#=#                                                              [10:31:06] ##O#- #                                                              [10:31:07] ##O=#  #                                                             [10:31:07] #=#=-#  #                                                            [10:31:07] -#O#- #   #                                                          [10:31:07]                                                                      [10:31:07] ##                                                                   [10:31:08] ######                                                               [10:31:08] ############                                                         [10:31:08] ##########################                                           [10:31:08] #######################################################              [10:31:08] ######################################################################## 100,0%
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
```

It can be fixed by running julia with SUDO

**Comment by ying17zi** [comment]
Just a report here: similar permission issue occurs on Mac with Julia 1.1. 
Fixed by the solution noted above: `$ sudo julia`.

```
(v1.1) pkg> build SymEngine
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/ne2iw/deps/build.log`
  Building SymEngine ───────→ `~/.julia/packages/SymEngine/zSUGO/deps/build.log`
┌ Error: Error building `SymEngine`: 
│ [ Info: /Users/hli/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libgmp.10.dylib
│ [ Info: /Users/hli/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpfr.6.dylib
│ [ Info: /Users/hli/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpc.3.dylib
│ [ Info: /Users/hli/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.0.4.0.dylib
│ [ Info: Found a valid dl path libgmp.10.dylib while looking for libgmp
│ [ Info: /Users/hli/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libgmp.10.dylib matches our search criteria of libgmp
│ [ Info: Found a valid dl path libgmp.10.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libgmp.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libgmpxx.4.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libgmpxx.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libmpc.3.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libmpc.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libmpfr.6.dylib while looking for libmpfr
│ [ Info: /Users/hli/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpfr.6.dylib matches our search criteria of libmpfr
│ [ Info: Found a valid dl path libgmp.10.dylib while looking for libmpc
│ [ Info: Found a valid dl path libgmp.dylib while looking for libmpc
│ [ Info: Found a valid dl path libgmpxx.4.dylib while looking for libmpc
│ [ Info: Found a valid dl path libgmpxx.dylib while looking for libmpc
│ [ Info: Found a valid dl path libmpc.3.dylib while looking for libmpc
│ [ Info: /Users/hli/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpc.3.dylib matches our search criteria of libmpc
│ [ Info: Found a valid dl path libgmp.10.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libgmp.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libgmpxx.4.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libgmpxx.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libmpc.3.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libmpc.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libmpfr.6.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libmpfr.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libsymengine.0.4.0.dylib while looking for libsymengine
│ [ Info: /Users/hli/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.0.4.0.dylib matches our search criteria of libsymengine
│ ERROR: LoadError: SystemError: opening file "/Users/hli/.julia/packages/SymEngine/zSUGO/deps/deps.jl": Permission denied
│ Stacktrace:
│  [1] #systemerror#43(::Nothing, ::Function, ::String, ::Bool) at ./error.jl:134
│  [2] systemerror at ./error.jl:134 [inlined]
│  [3] #open#309(::Nothing, ::Nothing, ::Nothing, ::Bool, ::Nothing, ::Function, ::String) at ./iostream.jl:283
│  [4] #open at ./none:0 [inlined]
│  [5] open(::String, ::String) at ./iostream.jl:339
│  [6] #open#310(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(BinaryProvider, Symbol("##154#158")){Bool,String,Array{LibraryProduct,1},getfield(BinaryProvider, Symbol("##153#157"))}, ::String, ::Vararg{String,N} where N) at ./iostream.jl:367
│  [7] open at ./iostream.jl:367 [inlined]
│  [8] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /Users/hli/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:419
│  [9] write_deps_file(::String, ::Array{LibraryProduct,1}) at /Users/hli/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:395
│  [10] top-level scope at none:0
│  [11] include at ./boot.jl:326 [inlined]
│  [12] include_relative(::Module, ::String) at ./loading.jl:1038
│  [13] include(::Module, ::String) at ./sysimg.jl:29
│  [14] include(::String) at ./client.jl:403
│  [15] top-level scope at none:0
│ in expression starting at /Users/hli/.julia/packages/SymEngine/zSUGO/deps/build.jl:60
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
```

```
➜  ~ sudo julia-1.1 
Password:
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.1) pkg> build SymEngine
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/ne2iw/deps/build.log`
  Building SymEngine ───────→ `~/.julia/packages/SymEngine/zSUGO/deps/build.log`

(v1.1) pkg> 
```

**Comment by ying17zi** [comment]
> ```
> (v1.1) pkg> build SymEngine
>   Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`
>   Building SymEngine ───────→ `~/.julia/packages/SymEngine/zSUGO/deps/build.log`
> ┌ Error: Error building `SymEngine`: 
> │ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libgmp.so
> │ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpfr.so
> │ [ Info: Downloading https://github.com/isuruf/MPCBuilder/releases/download/v1.1.0-3/MPC.v1.1.0.x86_64-linux-gnu.tar.gz to /home/kir/.julia/packages/SymEngine/zSUGO/deps/downloads/mpc-1.1.0/downloads/MPC.v1.1.0.x86_64-linux-gnu.tar.gz...
> │ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpc.so
> │ [ Info: Downloading https://github.com/symengine/SymEngineBuilder/releases/download/v0.4.0-3/build_SymEngine.v0.4.0.jl to /home/kir/.julia/packages/SymEngine/zSUGO/deps/downloads/build_97348aaf042e3c81b938ac665a0c81e02b5f4e5125d76cedcd2fc3c9dcb182df.jl...
> │ [ Info: Downloading https://github.com/symengine/SymEngineBuilder/releases/download/v0.4.0-3/SymEngine.v0.4.0.x86_64-linux-gnu.tar.gz to /home/kir/.julia/packages/SymEngine/zSUGO/deps/downloads/symengine-0.4.0/downloads/SymEngine.v0.4.0.x86_64-linux-gnu.tar.gz...
> │ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.so
> │ [ Info: Found a valid dl path libgmp.so while looking for libgmp
> │ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libgmp.so matches our search criteria of libgmp
> │ [ Info: Found a valid dl path libgmp.so while looking for libmpfr
> │ [ Info: Found a valid dl path libgmp.so.10 while looking for libmpfr
> │ [ Info: Found a valid dl path libgmp.so.10.3.2 while looking for libmpfr
> │ [ Info: Found a valid dl path libgmpxx.so while looking for libmpfr
> │ [ Info: Found a valid dl path libgmpxx.so.4 while looking for libmpfr
> │ [ Info: Found a valid dl path libgmpxx.so.4.5.2 while looking for libmpfr
> │ [ Info: Found a valid dl path libmpc.so while looking for libmpfr
> │ [ Info: Found a valid dl path libmpc.so.3 while looking for libmpfr
> │ [ Info: Found a valid dl path libmpc.so.3.1.0 while looking for libmpfr
> │ [ Info: Found a valid dl path libmpfr.so while looking for libmpfr
> │ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpfr.so matches our search criteria of libmpfr
> │ [ Info: Found a valid dl path libgmp.so while looking for libmpc
> │ [ Info: Found a valid dl path libgmp.so.10 while looking for libmpc
> │ [ Info: Found a valid dl path libgmp.so.10.3.2 while looking for libmpc
> │ [ Info: Found a valid dl path libgmpxx.so while looking for libmpc
> │ [ Info: Found a valid dl path libgmpxx.so.4 while looking for libmpc
> │ [ Info: Found a valid dl path libgmpxx.so.4.5.2 while looking for libmpc
> │ [ Info: Found a valid dl path libmpc.so while looking for libmpc
> │ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpc.so matches our search criteria of libmpc
> │ [ Info: Found a valid dl path libgmp.so while looking for libsymengine
> │ [ Info: Found a valid dl path libgmp.so.10 while looking for libsymengine
> │ [ Info: Found a valid dl path libgmp.so.10.3.2 while looking for libsymengine
> │ [ Info: Found a valid dl path libgmpxx.so while looking for libsymengine
> │ [ Info: Found a valid dl path libgmpxx.so.4 while looking for libsymengine
> │ [ Info: Found a valid dl path libgmpxx.so.4.5.2 while looking for libsymengine
> │ [ Info: Found a valid dl path libmpc.so while looking for libsymengine
> │ [ Info: Found a valid dl path libmpc.so.3 while looking for libsymengine
> │ [ Info: Found a valid dl path libmpc.so.3.1.0 while looking for libsymengine
> │ [ Info: Found a valid dl path libmpfr.so while looking for libsymengine
> │ [ Info: Found a valid dl path libmpfr.so.6 while looking for libsymengine
> │ [ Info: Found a valid dl path libmpfr.so.6.0.2 while looking for libsymengine
> │ [ Info: Found a valid dl path libsymengine.so while looking for libsymengine
> │ [ Info: /home/kir/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.so matches our search criteria of libsymengine
> │ ERROR: LoadError: SystemError: opening file "/home/kir/.julia/packages/SymEngine/zSUGO/deps/deps.jl": Permission denied
> │ Stacktrace:
> │  [1] #systemerror#43(::Nothing, ::Function, ::String, ::Bool) at ./error.jl:134
> │  [2] systemerror at ./error.jl:134 [inlined]
> │  [3] #open#309(::Nothing, ::Nothing, ::Nothing, ::Bool, ::Nothing, ::Function, ::String) at ./iostream.jl:289
> │  [4] #open at ./none:0 [inlined]
> │  [5] open(::String, ::String) at ./iostream.jl:345
> │  [6] #open#310(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(BinaryProvider, Symbol("##154#158")){Bool,String,Array{LibraryProduct,1},getfield(BinaryProvider, Symbol("##153#157"))}, ::String, ::Vararg{String,N} where N) at ./iostream.jl:373
> │  [7] open at ./iostream.jl:373 [inlined]
> │  [8] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/kir/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:419
> │  [9] write_deps_file(::String, ::Array{LibraryProduct,1}) at /home/kir/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:395
> │  [10] top-level scope at none:0
> │  [11] include at ./boot.jl:326 [inlined]
> │  [12] include_relative(::Module, ::String) at ./loading.jl:1038
> │  [13] include(::Module, ::String) at ./sysimg.jl:29
> │  [14] include(::String) at ./client.jl:403
> │  [15] top-level scope at none:0
> │ in expression starting at /home/kir/.julia/packages/SymEngine/zSUGO/deps/build.jl:60
> │ [10:31:02] #=#=#                                                              [10:31:03] ##O#- #                                                              [10:31:03] ##O=#  #                                                             [10:31:03] #=#=-#  #                                                            [10:31:03] -#O#- #   #                                                          [10:31:03] -=#=#   #   #                                                        [10:31:03] -=O#- #  #    #                                                      [10:31:03] -=O=#  #   #   #                                                     [10:31:04] ###############                                                      [10:31:05] ###############################################                      [10:31:05] ################################################                     [10:31:05] ######################################################################## 100,0%
> │ [10:31:05] #=#=#                                                              [10:31:05] ##O#- #                                                              [10:31:05] ##O=#  #                                                             [10:31:05] #=#=-#  #                                                            [10:31:06] -#O#- #   #                                                          [10:31:06] -=#=#   #   #                                                        [10:31:06] ######################################################################## 100,0%
> │ [10:31:06] #=#=#                                                              [10:31:06] ##O#- #                                                              [10:31:07] ##O=#  #                                                             [10:31:07] #=#=-#  #                                                            [10:31:07] -#O#- #   #                                                          [10:31:07]                                                                      [10:31:07] ##                                                                   [10:31:08] ######                                                               [10:31:08] ############                                                         [10:31:08] ##########################                                           [10:31:08] #######################################################              [10:31:08] ######################################################################## 100,0%
> └ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
> ```
> 
> 
> It can be fixed by running julia with SUDO

@kirtsar Do you have to `$ sudo julia` every time you want to use `SymEngine` (after building it with `sudo`)?
