### ISSUE TITLE
Build failure on MacOS, Julia 1.2

### ISSUE THREAD

**Issue by AshtonSBradley** [symengine/SymEngine.jl#176]
```julia 
(v1.2) pkg> build SymEngine
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`
  Building SymEngine ───────→ `~/.julia/packages/SymEngine/zSUGO/deps/build.log`
┌ Error: Error building `SymEngine`: 
│ [ Info: /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libgmp.10.dylib
│ [ Info: /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpfr.6.dylib
│ [ Info: /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpc.3.dylib
│ [ Info: /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.0.4.0.dylib
│ [ Info: Found a valid dl path libgmp.10.dylib while looking for libgmp
│ [ Info: /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libgmp.10.dylib matches our search criteria of libgmp
│ [ Info: Found a valid dl path libgmp.10.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libgmp.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libgmpxx.4.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libgmpxx.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libmpc.3.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libmpc.dylib while looking for libmpfr
│ [ Info: Found a valid dl path libmpfr.6.dylib while looking for libmpfr
│ [ Info: /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpfr.6.dylib matches our search criteria of libmpfr
│ [ Info: Found a valid dl path libgmp.10.dylib while looking for libmpc
│ [ Info: Found a valid dl path libgmp.dylib while looking for libmpc
│ [ Info: Found a valid dl path libgmpxx.4.dylib while looking for libmpc
│ [ Info: Found a valid dl path libgmpxx.dylib while looking for libmpc
│ [ Info: Found a valid dl path libmpc.3.dylib while looking for libmpc
│ [ Info: /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libmpc.3.dylib matches our search criteria of libmpc
│ [ Info: Found a valid dl path libgmp.10.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libgmp.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libgmpxx.4.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libgmpxx.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libmpc.3.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libmpc.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libmpfr.6.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libmpfr.dylib while looking for libsymengine
│ [ Info: Found a valid dl path libsymengine.0.4.0.dylib while looking for libsymengine
│ [ Info: /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.0.4.0.dylib matches our search criteria of libsymengine
│ ERROR: LoadError: SystemError: opening file "/Users/abradley/.julia/packages/SymEngine/zSUGO/deps/deps.jl": Permission denied
│ Stacktrace:
│  [1] #systemerror#44(::Nothing, ::typeof(systemerror), ::String, ::Bool) at ./error.jl:134
│  [2] systemerror at ./error.jl:134 [inlined]
│  [3] #open#311(::Nothing, ::Nothing, ::Nothing, ::Bool, ::Nothing, ::typeof(open), ::String) at ./iostream.jl:289
│  [4] #open at ./none:0 [inlined]
│  [5] open(::String, ::String) at ./iostream.jl:345
│  [6] #open#312(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(open), ::getfield(BinaryProvider, Symbol("##154#158")){Bool,String,Array{LibraryProduct,1},getfield(BinaryProvider, Symbol("##153#157")),SubString{String}}, ::String, ::Vararg{String,N} where N) at ./iostream.jl:373
│  [7] open at ./iostream.jl:373 [inlined]
│  [8] #write_deps_file#152(::Bool, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at /Users/abradley/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:419
│  [9] write_deps_file(::String, ::Array{LibraryProduct,1}) at /Users/abradley/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:395
│  [10] top-level scope at /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/build.jl:60
│  [11] include at ./boot.jl:328 [inlined]
│  [12] include_relative(::Module, ::String) at ./loading.jl:1094
│  [13] include(::Module, ::String) at ./Base.jl:31
│  [14] include(::String) at ./client.jl:431
│  [15] top-level scope at none:5
│ in expression starting at /Users/abradley/.julia/packages/SymEngine/zSUGO/deps/build.jl:60
└ @ Pkg.Operations /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/Pkg/src/backwards_compatible_isolation.jl:647
```

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by jverzani** [comment]
This seems to be an issue with the SpecialFunctions dependency.

**Comment by Roger-luo** [comment]
same issue, this breaks our CI now: https://travis-ci.com/QuantumBFS/YaoExtensions.jl/jobs/234537351

**Comment by isuruf** [comment]
@Roger-luo, where's the error in https://travis-ci.com/QuantumBFS/YaoExtensions.jl/jobs/234537351 ?

**Comment by Roger-luo** [comment]
Oh, sorry. It seems to be another error. But I do received reports of installing SymEngine. I thought it is "invalid". so it prints these info as long as it builds I guess.

**Comment by isuruf** [comment]
That Permission denied error might be because the user tried first with root privileges and then tried without privileges. Can you check?

**Comment by LWKJJONAK** [comment]
> Oh, sorry. It seems to be another error. But I do received reports of installing SymEngine. I thought it was "invalid". so it prints these info as long as it builds I guess.
> 
> <img alt="AE0CF6D3F5651A3B5AB91E396481D6DA" width="1100" src="https://user-images.githubusercontent.com/8445510/65469093-26ac4300-de34-11e9-94dc-87c6d2dc7283.png">

Hi I'm a Qualgorithmzoo user but i'm not very good at dealing these issues.Can we get back to the previous version or is there any thing we can do to deal with the "Error building `SymEngine`"?

**Comment by Roger-luo** [comment]
> Can we get back to the previous version

There is no previous version, QuAlgorithmZoo is not a package, it is just demos and examples.

> is there any thing we can do to deal with the "Error building SymEngine"

I don't think this is our issue, it is probably because you install julia with root (sudo) access but your package do not have the access. I cannot repeat this issue on my own devices.

**Comment by LWKJJONAK** [comment]
> > Can we get back to the previous version
> 
> There is no previous version, QuAlgorithmZoo is not a package, it is just demos and examples.
> 
> > is there any thing we can do to deal with the "Error building SymEngine"
> 
> I don't think this is our issue, it is probably because you install julia with root (sudo) access but your package do not have the access. I cannot reproduce this issue on my own devices.

Thanks for your reply! My julia-1.0.5 on mac and linux meets the same "permission denied" as the author of this open issue. Do you mean this is not a bug and it comes from the wrong installation?(everything is ok before i put in "Pkg>update" and click enter, then suddenly i can't build the symengine or use the QuAlgoZoo)

**Comment by Roger-luo** [comment]
can you `ls -l` the `.julia` folder?

> it comes from the wrong installation

julia won't be able to do any modification in the path if there is no permission, I think the error msg I posted is originally from you. and I do not think this is an actual issue/bug now.

**Comment by LWKJJONAK** [comment]
> can you `ls -l` the `.julia` folder?
> 
> > it comes from the wrong installation
> 
> julia won't be able to do any modification in the path if there is no permission, I think the error msg I posted is originally from you. and I do not think this is an actual issue/bug now. The simplest solution I can see is to delete your .julia folder and reinstall all the packages.

Thanks, I just delete all the packages and reinstall them. Now everything goes right and thank you for your patience!

**Comment by AshtonSBradley** [comment]
yeah, deleting .julia fixed it for me

**Comment by isuruf** [comment]
Thanks for confirming.
