### ISSUE TITLE
printing imaginary unit as `im`?

### ISSUE THREAD

**Issue by Roger-luo** [symengine/SymEngine.jl#178]
Hi I'm wondering if it is possible to print imaginary unit as `im` which is more consistent with Julia, the current one `I` is sometimes confusing with the `LinearAlgebra.I`.

**Comment by isuruf** [comment]
We already have specializations for NaN, Infty and E for Julia in https://github.com/symengine/symengine/blob/master/symengine/printers/strprinter.cpp. We should fix `I` as well.

**Comment by certik** [comment]
A related issue for parsing: https://github.com/symengine/symengine/issues/1462
