### ISSUE TITLE
SymEngine Build Issues

### ISSUE THREAD

**Issue by ChrisRackauckas** [symengine/SymEngine.jl#180]
```
(v1.1) pkg> build SymEngine
  Building SpecialFunctions → `C:\Users\accou\.julia\packages\SpecialFunctions\fvheQ\deps\build.log`
  Building SymEngine ───────→ `C:\Users\accou\.julia\packages\SymEngine\zSUGO\deps\build.log`
┌ Error: Error building `SymEngine`:
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075
```

That's all it gives.

**Comment by isuruf** [comment]
Is `C:\Users\accou\.julia\packages\SymEngine\zSUGO\deps\build.log` empty?

**Comment by ChrisRackauckas** [comment]
Yes it's empty.

**Comment by nudigamma** [comment]
Hi , 
I have a similar problem,  on Julia 1.3 the PR is not merged yet ?
Pkg.build("SymEngine")
   Building SymEngine → `~/.juliapro/JuliaPro_v1.3.1-1/packages/SymEngine/RK5Ks/deps/build.log`
┌ Error: Error building `SymEngine`: 
│ ERROR: LoadError: SystemError: opening file "/home/nadim/.juliapro/JuliaPro_v1.3.1-1/packages/SymEngine/RK5Ks/deps/downloads/build_49205602a6121affc12e2c8039f21fd7fe079f328abaa9294d7cd804ac1769cb.jl": No such file or directory
