### ISSUE TITLE
Error using subs and Dictionnaire

### ISSUE THREAD

**Issue by Myrddinlefou** [symengine/SymEngine.jl#197]
Hello, 

I try to use subs with Dictionnaire and I did not understand why, on my cod, the calcul dUc1, dIl1 are not equal to dUc2, dIc2 :
```
using SymEngine
@vars Uin, Iin, Il, Ul, Id, Uc, Ic, Uout, Iout, Rout, C, L

dUc1 = subs(Ic/C,Ic=>Il-Iout,Iout=>Rout*Uout, Uout=>Uc)
dIl1 = subs(Ul/L, Ul=>Uin-Uout, Uout=>Uc)

DictChange= Dict(Ic=>Il-Iout, Iout => Rout*Uout, Uout => Uc)
DictChange2 = Dict(Ul=>Uin-Uout, Uout=>Uc)

dUc2 = subs(Ic/C, DictChange)
dIl2 = subs(Ul/C, DictChange2)
```
Thanks for your help.

**Comment by isuruf** [comment]
Which SymEngine.jl version are you using?
Can you show the values of `dUc1, dIl1, dUc2, dIl2` that you get?

**Comment by Myrddinlefou** [comment]
I use SymEngine v0.7.1, 
dIl1 = (-Uc + Uin)/L
dUc1 = (Il-Uc*Rout)/C
dIl2 = U1/C
dUc2 = Ic/C

I need the result of the first subs, but with Dictionnaire like in the second subs…

**Comment by isuruf** [comment]
@Myrddinlefou, can you try master?

**Comment by Myrddinlefou** [comment]
How can I try master ?

**Comment by isuruf** [comment]
Use a Pkg prompt (Enter `]`) and enter `dev SymEngine`.

```
(v1.3) pkg> dev SymEngine
```

**Comment by Myrddinlefou** [comment]
I try with dev SymEngine, but with this my Julia does not work. 

I have to update atom, and I try again tomorrow.

**Comment by Myrddinlefou** [comment]
I do not know what change with the master, but it work better. The only problem is I have to call multiple subs on the answer to have the final results. 
I am not surprise of this.

**Comment by isuruf** [comment]
> The only problem is I have to call multiple subs on the answer to have the final results.

Yes, that's how dictionary substitution is supposed to work. Since it is a container without a specific order, we treat the substitution as without order. Your first example does the substitution 3 times under the hood, but the dictionary substitution is only 1 time under the hood.
