### ISSUE TITLE
Problem with multi-threads

### ISSUE THREAD

**Issue by zhaoli-IHEP** [symengine/SymEngine.jl#200]
We found that the default version of SymEngine.jl in Julia1.3.1 does not support multi-thread programming. And we found #166 claims SymEngineBuilder could help. However, it can be seen in build_tarballs.jl that it downloads SymEngine.jl v0.5.0 to build. Does it mean the multi-threads is only available for v0.5.0? And even though we confront the error to use build_tarballs.jl 
```bash
[ ~/works/public_code/SymEngineBuilder @XEON ]:zhaoli$ julia build_tarballs.jl --help
WARNING: using HTTP.stack in module Mux conflicts with an existing identifier.
ERROR: LoadError: UndefVarError: expand_gcc_versions not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:13
 [2] top-level scope at /home/zhaoli/works/public_code/SymEngineBuilder/build_tarballs.jl:29
 [3] include at ./boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1105
 [5] include(::Module, ::String) at ./Base.jl:31
 [6] exec_options(::Base.JLOptions) at ./client.jl:287
 [7] _start() at ./client.jl:460
in expression starting at /home/zhaoli/works/public_code/SymEngineBuilder/build_tarballs.jl:29
```
Do we have different solution in the current version?

**Comment by isuruf** [comment]
Can you try https://github.com/symengine/SymEngine.jl/pull/186 ?

**Comment by zhaoli-IHEP** [comment]
> Can you try #186 ?

Do you mean that I have to manually change Project.toml in SymEngine.jl source code and build again? Then it will support multi-threads?

**Comment by isuruf** [comment]
Try doing `pkg> add SymEngine#master` in Julia 1.3

**Comment by zhaoli-IHEP** [comment]
> Try doing `pkg> add SymEngine#master` in Julia 1.3

Thank you for this interesting information. However, it seems version conflict appears.
```julia
(v1.3) pkg> add SymEngine#master
  Updating git-repo `https://github.com/symengine/SymEngine.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package RecipesBase [3cdcf5f2]:
 RecipesBase [3cdcf5f2] log:
 ├─possible versions are: [0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0] or uninstalled
 ├─restricted to versions 0.8 by SymEngine [123dc426], leaving only versions 0.8.0
 │ └─SymEngine [123dc426] log:
 │   ├─possible versions are: 0.7.1 or uninstalled
 │   └─SymEngine [123dc426] is fixed to version 0.7.1
 └─restricted by compatibility requirements with Measurements [eff96d63] to versions: [0.6.0, 0.7.0] — no versions left
   └─Measurements [eff96d63] log:
     ├─possible versions are: [1.0.0-1.0.2, 2.0.0, 2.1.0-2.1.1, 2.2.0] or uninstalled
     └─restricted to versions 2.2.0 by an explicit requirement, leaving only versions 2.2.0
```

**Comment by isuruf** [comment]
Can you try again? I just merged a PR to master.

**Comment by zhaoli-IHEP** [comment]
> Can you try again? I just merged a PR to master.

Thank you so much. Now it works perfectly.
So just for understanding, this will use the github version of SymEngine instead of the release version, is it right?
And in the future for update, is it just to use `pkg> update SymEngine` to fetch latest github version?
Also can we just use `pkg> add SymEngine` to switch back to release version?

**Comment by isuruf** [comment]
0.8.0 version has this now
