### ISSUE TITLE
Can diff work with arrays? `diff([cos(x),sin(x),x]` returns an error.

### ISSUE THREAD

**Issue by johnalx** [symengine/SymEngine.jl#205]
I am trying to use `SymEngine` with arrays of expressions. See example below

    using SymEngine
    @vars x
    diff( [cos(x), sin(x)], x)
    ERROR: MethodError: no method matching diff(::Array{Basic,1}, ::Basic)

Even more important is to be able to generate a gradient matrix by differentiating each element of a vector expression with each symbolic variable.

    @vars a b
    expr = [ a^2+2*b^2, -a*b]
    f = diff(expr, [a,b])
    #  expected result 2×2 matrix: [ 2a -b; 4a -a]

**Comment by isuruf** [comment]
```julia
julia> using SymEngine

julia> @vars x y
(x, y)

julia> diff.([cos(x), sin(x)], x)
2-element Array{Basic,1}:
 -sin(x)
  cos(x)
```

**Comment by isuruf** [comment]
For the second example,
```julia
julia> @vars a b
(a, b)

julia> expr = [ a^2+2*b^2, -a*b]
2-element Array{Basic,1}:
 a^2 + 2*b^2
        -a*b

julia> diff.(expr, transpose([a, b]))
2×2 Array{Basic,2}:
 2*a  4*b
  -b   -a
```

**Comment by johnalx** [comment]
> For the second example,
> 
> ```julia
> julia> @vars a b
> (a, b)
> 
> julia> expr = [ a^2+2*b^2, -a*b]
> 2-element Array{Basic,1}:
>  a^2 + 2*b^2
>         -a*b
> 
> julia> diff.(expr, transpose([a, b]))
> 2×2 Array{Basic,2}:
>  2*a  4*b
>   -b   -a
> ```

Thank you. Care to explain why the dot notation is necessary here? I am new to Julia notation. I understand that in the context of matrix multiplication .* does it by element (like Matlab) and how * operates in Fortran. I am also familiar with the symbolic toolbox in Matlab which does _not_ require a vectoring dot modifier.

**Comment by jverzani** [comment]
The "dot" does broadcasting (cf. ?broadcast) and is more generally integrated into the language than MATLAB where it is mostly with operators (as I remember, it has been a while). Matlab has most functions vectorized, whereas  in  Julia,  one indicates vectorization  through broadcasting (the dot).

**Comment by Gyoshi** [comment]
Seems like this should be closed

**Comment by isuruf** [comment]
Closing as this is how Julia works
