### ISSUE TITLE
Returning a variable from a module cause segmentation fault.

### ISSUE THREAD

**Issue by newptcai** [symengine/SymEngine.jl#208]
The following code works in REPL
```
module MyM
using SymEngine
export beta, return_beta
@vars beta
function return_beta()
    return -beta
end
end
MyM.return_beta()
```
But once you save the module into a file and use it like this
```
using MyM; MyM.return_beta()
```
You will see a segmentation fault.

**Comment by isuruf** [comment]
Yes, this is an issue with serialization. https://github.com/symengine/SymEngine.jl/issues/198
