### ISSUE TITLE
Using `diff()` with tuples and arrays

### ISSUE THREAD

**Issue by johnalx** [symengine/SymEngine.jl#213]
Although `diff()` seems to work with scalar values such as

    @vars t
     diff( cos(t), t)    # = -sin(t)

it does not work on tuples

    @vars t
    pos = (cos(t), sin(t))
    dif( pos, t)  #error

or arrays

    @vars t
    pos = [cos(t), sin(t), 0.0]
    dif( pos, t)  #error

Are there plans to make `::Basic` types work with `Calculus.diff` and `Calculus.jacobian`?

**Comment by isuruf** [comment]
Isn't this a duplicate of https://github.com/symengine/SymEngine.jl/issues/205 ?

**Comment by johnalx** [comment]
Duplicate issue.
