### ISSUE TITLE
Support macos aarch64 package install

### ISSUE THREAD

**Issue by agascoig** [symengine/SymEngine.jl#240]
There does not appear to be a wrapper yet for Apple silicon on macos.

**Comment by isuruf** [comment]
@agascoig, can you open this in https://github.com/JuliaPackaging/Yggdrasil? We only need SymEngine_jll.jl which is generated by that repo

**Comment by giordano** [comment]
@isuruf in order to build SymEngine_jll for the new architecture we must require Julia v1.6, are you ok with that?  Of course older versions of the package will still work on Julia v1.3+, but updates will be available only for v1.6+.

**Comment by agascoig** [comment]
Yes, that is fine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by isuruf** [comment]
@giordano, that's fine

**Comment by giordano** [comment]
BTW, I can confirm that `master` version of this package + v0.8.1 of `SymEngine_jll` works fine on M1, at least tests pass.

**Comment by isuruf** [comment]
Thanks @giordano for testing
