### ISSUE TITLE
Issues with Saving

### ISSUE THREAD

**Issue by chelseas** [symengine/SymEngine.jl#242]
I have been having issues with saving Basic variables and also with using them in multiprocessing.
I started an issue on the JLD2 repo, and someone clued me in to the fact that they wrap an actual memory pointer.
I think that one solution might be to convert to Expr and/or Symbol (depending on what's appropriate) before saving. I have used both extensively and I am pretty sure the conversion is lossless. 
TBH I wish that algebraic operations worked for Symbol and Expr directly, but that might be another project for another time haha. 

Some folks suggested I bring it up this saving issue here. Here is the thread:
https://github.com/JuliaIO/JLD2.jl/issues/362

Thoughts?

**Comment by PerformanceCoder** [comment]
Perhaps it is relative to #198 ?
