### ISSUE TITLE
Update SymEngine_jll

### ISSUE THREAD

**Issue by PerformanceCoder** [symengine/SymEngine.jl#251]
Hi!

Currently, the version of SymEngine_jll is based on SymEngine v0.8.1+0, which was published in Nov 2021. The latest version of SymEngine supports serialization, but Julia-wrapper can't use it because of an old version of jll. Could you update it?

This will fix CI check for commit #246. Also, after updating jll I could add another PR for serialization/deserialization which will potentially fix #242 and #198 and allow the use of SymEngine for multiprocessing and distributed computing.

**Comment by isuruf** [comment]
Please open an issue in https://github.com/JuliaPackaging/Yggdrasil about updating SymEngine_jll.

**Comment by PerformanceCoder** [comment]
Ready
