### ISSUE TITLE
Use Conda.jl for binary dependencies

### ISSUE THREAD

**Issue by isuruf** [symengine/SymEngine.jl#29]
See, https://github.com/Luthaf/Conda.jl

**Comment by spencerlyon2** [comment]
This is a great idea.

Any idea how difficult it would be to get binaries for all major platforms up on conda? Would we utilize [conda-forge](https://conda-forge.github.io) for this?

**Comment by isuruf** [comment]
There are conda-forge packages already. https://github.com/conda-forge/symengine-feedstock
