### ISSUE TITLE
Some possible new methods to add to support generic programming

### ISSUE THREAD

**Issue by jverzani** [symengine/SymEngine.jl#54]
I'm not sure the following suggestions are the best way to do this, but it seems the following could be added to support generic programming:

`isinf(x::SymbolicType) = isinf(N(x))`

`isfinite(x::SymbolicType) = isfinite(N(x))`

`isnan(x::SymbolicType) = isnan(N(x))`

`isless(x::SymbolicType, y::SymbolicType) = N(x) < N(y)`

As well, there is no `call` method. Following `SymPy.jl` these could be defined by

```
function (ex::SymbolicType)(args...)
     xs = free_symbols(ex)
    subs(ex, collect(zip(xs, args))...)
end
(ex::SymbolicType)(x::Dict) = subs(ex, x)
(ex::SymbolicType)(x::Pair...) = subs(ex, x...)   
```

or for v0.4:

```
function Base.call{T <: SymbolicType}(ex::T, args...)
   xs = free_symbols(ex)
   subs(ex, collect(zip(xs, args))...)
end
Base.call(ex::SymbolicType, x::Dict) = subs(ex, x)
Base.call(ex::SymbolicType, x::Pair...) = subs(ex, x...)
```

Finally, I was surprised that there is no conversion defined for Float64. Would something like this be reasonable:

```
Base.convert{T <: Real}(::Type{T}, x::Basic) = convert(T, N(x))
Base.convert{T}(::Type{Complex{T}}, x::Basic) = convert(Complex{T}, N(x))
```

**Comment by isuruf** [comment]
Looks good to me.
We should change `N` to use `evalf` instead of `lambdify` as `evalf` supports arbitrary precision numerics and is faster.

**Comment by jverzani** [comment]
I have a question about `N` versus `evalf`. In the `SymPy.jl` package I separated the meaning so that `N` found a representation in `julia` for the object, whereas `evalf` left the numeric value as a SymPy object. This distinction carried over to SymEngine, but perhaps it isn't the best. I still kinda like it, but I could just be partial. So replacing `N` for `evalf` might not be appropriate. As for `lambdify` that is just a catch all, aren't most cases caught earlier and converted appropriately?

**Comment by certik** [comment]
@jverzani perhaps we can add an optional argument to N() or evalf() where the user can tell if he wants julia or sympy/symengine object.

**Comment by jverzani** [comment]
Might be best to  just make sure the `convert(T, x::Basic)` methods work. As it is now, very few are defined, except for special underlying types. This way, users can explicitly call `Float64(x)`, say, to get values to use within `julia`. With this, `N` and `evalf` can be as they are within SymEngine.
