### ISSUE TITLE
SymEngine Build Errors

### ISSUE THREAD

**Issue by ChrisRackauckas** [symengine/SymEngine.jl#64]
All of my tests have suddenly started failing due to SymEngine build errors.

https://travis-ci.org/JuliaDiffEq/DiffEqCallbacks.jl/jobs/191380659
https://travis-ci.org/JuliaDiffEq/DiffEqMonteCarlo.jl/jobs/191380533

Same error each time. This wasn't happening earlier this morning.

**Comment by isuruf** [comment]
Server error at anaconda.org. Should be resolved now. https://github.com/conda/conda/issues/4287
