### ISSUE TITLE
Problem building the package. Issue with miniconda

### ISSUE THREAD

**Issue by adrianor** [symengine/SymEngine.jl#65]
I have a problem while building the package.

This is my full error window.

`julia> Pkg.build("SymEngine")`
INFO: Building Conda
INFO: Building SymEngine
INFO: Downloading miniconda installer ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
============================[ ERROR: SymEngine ]============================

LoadError: failed process: Process(`curl -o /home/jivifair/.julia/v0.5/Conda/deps/usr/installer.sh -L http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh`, ProcessExited(77)) [77]
while loading /home/jivifair/.julia/v0.5/SymEngine/deps/build.jl, in expression starting on line 9

============================================================================

==============================[ BUILD ERRORS ]==============================

WARNING: SymEngine had build errors.

 - packages with build errors remain installed in /home/jivifair/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("SymEngine")`
 - build a single package by running its `deps/build.jl` script

============================================================================`

**Comment by ChrisRackauckas** [comment]
Do you have a previous Conda installation? It might be related to this?

https://github.com/symengine/SymEngine.jl/issues/56#issuecomment-271427446

**Comment by adrianor** [comment]
Actually yes, I have Anaconda from which I use the jupyter notebook.

Is there a workaround?

**Comment by isuruf** [comment]
@adrianor, can you run the following commands and see if either of them fail?
```Julia
julia> download("http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh", "/home/jivifair/.julia/v0.5/Conda/deps/usr/installer.sh")

julia> download("https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh", "/home/jivifair/.julia/v0.5/Conda/deps/usr/installer.sh")
```

**Comment by adrianor** [comment]
Both of them fail

`julia> download("http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh", "/home/jivifair/.julia/v0.5/Conda/deps/usr/installer.sh")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Failed to create the file 
Warning: /home/jivifair/.julia/v0.5/Conda/deps/usr/installer.sh: No such file 
Warning: or directory
  0 25.9M    0   833    0     0   3233      0  2:20:15 --:--:--  2:20:15  3233
curl: (23) Failed writing body (0 != 833)
ERROR: failed process: Process(`curl -o /home/jivifair/.julia/v0.5/Conda/deps/usr/installer.sh -L http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh`, ProcessExited(23)) [23]
 [inlined code] from ./error.jl:22
 in pipeline_error(::Base.Process) at ./process.jl:622
 [inlined code] from ./process.jl:598
 in download(::String, ::String) at ./interactiveutil.jl:444
 in eval(::Module, ::Any) at ./boot.jl:226`

`julia> download("https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh", "/home/jivifair/.julia/v0.5/Conda/deps/usr/installer.sh")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 
Warning: /home/jivifair/.julia/v0.5/Conda/deps/usr/installer.sh: No such file 
Warning: or directory
  0 25.9M    0   833    0     0   6147      0  1:13:46 --:--:--  1:13:46  6216
curl: (23) Failed writing body (0 != 833)`

`ERROR: failed process: Process(`curl -o /home/jivifair/.julia/v0.5/Conda/deps/usr/installer.sh -L https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh`, ProcessExited(23)) [23]
 [inlined code] from ./error.jl:22
 in pipeline_error(::Base.Process) at ./process.jl:622
 [inlined code] from ./process.jl:598
 in download(::String, ::String) at ./interactiveutil.jl:444
 in eval(::Module, ::Any) at ./boot.jl:226`

**Comment by isuruf** [comment]
@adrianor, thanks for the info. Can you try creating the folder, `/home/jivifair/.julia/v0.5/Conda/deps/usr` and then running those 2 commands again?

**Comment by isuruf** [comment]
Can't reproduce this issue. Please feel free to reopen or create a new issue if you run into this again
