### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by wupeifan** [symengine/SymEngine.jl#66]
I encountered an error while running runtests.jl file. It was  on Win10 with Julia 0.5.0. Error messages are the following:

> (1/2)*x - 5*x*y + x^2
1/2 + 2*x - 5*y
Error During Test
  Test threw an exception of type MethodError
  Expression: 
N(Basic(val)) == val
  MethodError: objects of type Int64 are not callable
   in macro expansion; at tmp.jl:118 [inlined]
   in anonymous at .\<missing>:?
   in include_string(::String, ::String) at .\loading.jl:441
   in include_string(::Module, ::String, ::String) at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\CodeTools\src\eval.jl:32
   in (::Atom.##61#64{String,String})() at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\Atom\src\eval.jl:81
   in withpath(::Atom.##61#64{String,String}, ::String) at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\CodeTools\src\utils.jl:30
   in withpath(::Function, ::String) at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\Atom\src\eval.jl:46
   in macro expansion at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\Atom\src\eval.jl:79 [inlined]
   in (::Atom.##60#63{String,String})() at .\task.jl:60

**Comment by isuruf** [comment]
Thanks for the bug report. Can you run the following in Julia and send the output?

```Julia
using SymEngine
samples = (1, 1//2, (1 + 2im), 1.0, (1.0 + 0im))
for val in samples
    @test N(Basic(val)) == val
end
```

**Comment by wupeifan** [comment]
It works fine. I think that's because I was running inside an environment which redefined something.
After I cleared the environment and ran test file again, the following error showed up,

> Error During Test
  Test threw an exception of type 
MethodError
  Expression: 
norm(simple_newton(sin(x),diff(sin(x),x),3) - pi) <= 
1.0e-14
  MethodError: objects of type SymEngine.Basic are not callable
   in simple_newton(::SymEngine.Basic, ::SymEngine.Basic, ::Int64) at .\untitled:137
   in include_string(::String, ::String) at .\loading.jl:441
   in include_string(::Module, ::String, ::String) at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\CodeTools\src\eval.jl:32
   in (::Atom.##61#64{String,String})() at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\Atom\src\eval.jl:81
   in withpath(::Atom.##61#64{String,String}, ::String) at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\CodeTools\src\utils.jl:30
   in withpath(::Function, ::String) at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\Atom\src\eval.jl:46
   in macro expansion at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\Atom\src\eval.jl:79 [inlined]
   in (::Atom.##60#63{String,String})() at .\task.jl:60

**Comment by wupeifan** [comment]
And then I ran a similar line in a clear environment, which could be helpful to find out what happened above,

`using SymEngine
Float64(Basic(4.0))`

and it returned

> MethodError:
Cannot `convert` an object of type SymEngine.Basic to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
 in Float64(::SymEngine.Basic) at .\sysimg.jl:53
 in include_string(::String, ::String) at .\loading.jl:441
 in eval(::Module, ::Any) at .\boot.jl:234
 in (::Atom.##67#70)() at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\Atom\src\eval.jl:40
 in withpath(::Atom.##67#70, ::Void) at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\CodeTools\src\utils.jl:30
 in withpath(::Function, ::Void) at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\Atom\src\eval.jl:46
 in macro expansion at C:\Program Files\Julia-0.5.0\juliapackages\v0.5\Atom\src\eval.jl:109 [inlined]
 in (::Atom.##66#69)() at .\task.jl:60

**Comment by isuruf** [comment]
Can you try building SymEngine? This looks like SymEngine code you are running is older, but the tests are you are running are newer.

**Comment by wupeifan** [comment]
I rebuild it through `Pkg.build("SymEngine")` and it didn't work.  SymEngine version is 0.1.2

> julia> using SymEngine

julia> Float64(Basic(4.0))
ERROR: MethodError: Cannot `convert` an object of type SymEngine.Basic to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
 in Float64(::SymEngine.Basic) at .\sysimg.jl:53

julia> Pkg.test("SymEngine")
INFO: Testing SymEngine
(1/2)*x - 5*x*y + x^2
1/2 + 2*x - 5*y
INFO: SymEngine tests passed

**Comment by wupeifan** [comment]
@isuruf  You are right - the code that I was running is an older version. I rebuilt it and it doesn't work out.
