### ISSUE TITLE
On creating an array of variables and pulling variables out of expressions

### ISSUE THREAD

**Issue by wupeifan** [symengine/SymEngine.jl#67]
I have two questions:
1. How to create an array of symbolic variables at one time? Say, "x1,x2,...,x100"
2. How to pull out the list of symbolic variables that appears in an expressions? Say, pulling out ["x", "y"] from "x+y" where those are two symbols.
I looked into test files but found nothing. I'd appreciate if you shed light on them,

**Comment by ChrisRackauckas** [comment]
>How to create an array of symbolic variables at one time? Say, "x1,x2,...,x100"

Just used string interpolation: `symbol("x$i")`.

**Comment by isuruf** [comment]
> How to pull out the list of symbolic variables that appears in an expressions? Say, pulling out ["x", "y"] from "x+y" where those are two symbols.

`free_symbols(x + y)`

**Comment by wupeifan** [comment]
I see. Thank both for you for your help!
