### ISSUE TITLE
Wrap `basic_subs`

### ISSUE THREAD

**Issue by isuruf** [symengine/SymEngine.jl#71]
Function signature can be, `subs(ex::Basic, d::Dict)`

**Comment by wupeifan** [comment]
Is there any function existing similar to this? i.e., evaluate expression with multiple variable-value substitutions.

**Comment by isuruf** [comment]
Following works,
```
expr = x^2 + y^2
subs(expr, x=>3, y=>4)
```
and gives 25

But note that this substitution is not simultaneous. so
```
expr = x ^ 2 + y ^ 2
subs(expr, x=>y, y=>x)
```
gives `2*x^2` instead of `x^2 + y^2`

wrapping `basic_subs` should give this funtionality
