### ISSUE TITLE
Lambdify and BigInts 

### ISSUE THREAD

**Issue by dgevans** [symengine/SymEngine.jl#74]
Hi,

I've been running into a problem with Lambdify.  Specifically, that it produces BigInts inside the expressions it generates.  For example, a derivative of one of the functions I am using is given by

`0. + 1.01010101010101*c^(-0.684931506849315)*E^(-(0.0015 + ϵ_Θ))/EUcM.`

What Lambdify constructs an expression for the function it creates

`0. + 1.01010101010101*c^(-0.684931506849315)*e^(-1*(0.0015 + ϵ_Θ))*EUcM^(-1)`

with both of the -1s being of type BigInt.  The resulting lambda function runs 10 times slower than if I redid the expression converting the -1s to floats, i.e. 

`0. + 1.01010101010101*c^(-0.684931506849315)*e^(-1.0*(0.0015 + ϵ_Θ))*EUcM^(-1.0)`

Is there any way to tell SymEngine to convert to Int64 rather that BigInt?  The extra precision is unnecessary for me, and the resulting code will be used in the innermost loop of my numeric simulations.  This is a fantastic library.  Thank you for all your work.

David

**Comment by isuruf** [comment]
Fixed in #75
