### ISSUE TITLE
Use basic_str_julia instead of basic_str

### ISSUE THREAD

**Issue by ChrisRackauckas** [symengine/SymEngine.jl#77]
`exp` is more optimized, and `E^` is only a SymEngine variable. If the `E^` expression is used to generate a Julia function, and this is run in a scope without SymEngine.jl in the namespace, then it will fail.

**Comment by isuruf** [comment]
I've opened an issue here, https://github.com/symengine/symengine/issues/1225

**Comment by ChrisRackauckas** [comment]
This is solved by the Julia printer.

**Comment by ChrisRackauckas** [comment]
https://github.com/symengine/symengine/pull/1246

**Comment by isuruf** [comment]
I'm reopening this since this is not fixed in julia
