### ISSUE TITLE
Warnings on executing Pkg.test("SymEngine")

### ISSUE THREAD

**Issue by kunal-iitkgp** [symengine/SymEngine.jl#9]
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 in depwarn at deprecated.jl:73
 in call at deprecated.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/kunal/.julia/v0.4/SymEngine/src/SymEngine.jl, in expression starting on line 57
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near /home/kunal/.julia/v0.4/SymEngine/src/SymEngine.jl:58
WARNING: Base.Uint16 is deprecated, use UInt16 instead.
  likely near /home/kunal/.julia/v0.4/SymEngine/src/SymEngine.jl:58
WARNING: Base.Uint32 is deprecated, use UInt32 instead.
  likely near /home/kunal/.julia/v0.4/SymEngine/src/SymEngine.jl:58
WARNING: Base.Uint64 is deprecated, use UInt64 instead.
  likely near /home/kunal/.julia/v0.4/SymEngine/src/SymEngine.jl:58
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 in depwarn at deprecated.jl:73
 in call at deprecated.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/kunal/.julia/v0.4/SymEngine/src/SymEngine.jl, in expression starting on line 58
WARNING: module SymEngine should explicitly import + from Base
WARNING: module SymEngine should explicitly import / from Base
WARNING: module SymEngine should explicitly import * from Base
WARNING: module SymEngine should explicitly import ^ from Base
WARNING: module SymEngine should explicitly import - from Base
WARNING: module SymEngine should explicitly import \ from Base
WARNING: module SymEngine should explicitly import == from Base
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 in depwarn at deprecated.jl:73
 in call at deprecated.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/kunal/.julia/v0.4/SymEngine/src/SymEngine.jl, in expression starting on line 112
WARNING: module SymEngine should explicitly import == from Base
WARNING: module SymEngine should explicitly import == from Base

**Comment by certik** [comment]
Is this something new in Julia 0.4?

**Comment by kunal-iitkgp** [comment]
Yes. I was going through  the manual of both Julia 0.3 and Julia 0.4 , what I found is that Julia 0.4 has some changes in the names of few numeric types like `UInt8` instead of `Uint8`. 
I will send a PR to fix this depreciation issue

**Comment by certik** [comment]
Thanks! We appreciate it.

**Comment by isuruf** [comment]
Closed via #10
