### ISSUE TITLE
Get a list of variables from an expression

### ISSUE THREAD

**Issue by kindlychung** [symengine/SymEngine.jl#97]
For example,

```julia
@vars x1 x2
X = x1^2 + (x2 + 1)^2 
Y = diff(X, x1) # involves only x1
X = x2 * x1^2 + (x2 + 1)^2 
Y = diff(X, x1) # involves both x1 and x2
```
`Y` is a partial derivative of `X`, but the number of variables in `Y` depends on how `X` is formulated. For the realization of `Y`, one needs to know what variables it contains.

**Comment by isuruf** [comment]
`free_symbols(ex)` gives the list of free symbols.
