### ISSUE TITLE
Erorr: SymFunction and @funs have not been defined

### ISSUE THREAD

**Issue by nhannguyen123** [symengine/SymEngine.jl#99]
I'm using the latest version and testing the test folder. Below is the error. Could you recheck it? Thanks.
![error-symengine jl](https://user-images.githubusercontent.com/21138008/27993043-906633a8-64cb-11e7-8621-e1113413f780.png)

**Comment by jverzani** [comment]
As far as I know, this feature is not in SymEngine, but it is in SymPy. In `SymPy.jl` you have the constructor `SymFunction` and macro `@symfuns` (called without a comma).

**Comment by nhannguyen123** [comment]
@jverzani . Thanks. After using SymPy, I can defined the symbolic function $f$
```Julia
using PyCall
using SymPy
@vars x y
f = SymFunction("f")
```
However, the next function
```Julia
f(x,y)
```
comes to error
~~~~
PyError (:PyObject_Call) <class 'sympy.core.sympify.SympifyError'>
SympifyError()
  File "/usr/lib/python2.7/dist-packages/sympy/core/function.py", line 616, in __new__
    args = list(map(sympify, args))
  File "/usr/lib/python2.7/dist-packages/sympy/core/sympify.py", line 315, in sympify
    raise SympifyError('could not parse %r' % a, exc)


 in pyerr_check at /home/nhan/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /home/nhan/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /home/nhan/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::PyCall.PyObject, ::Vararg{PyCall.PyObject,N}) at /home/nhan/.julia/v0.5/PyCall/src/PyCall.jl:596
 in _pycall(::PyCall.PyObject, ::PyCall.PyObject, ::Vararg{PyCall.PyObject,N}) at /home/nhan/.julia/v0.5/PyCall/src/PyCall.jl:584
 in #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::PyCall.PyObject, ::Vararg{PyCall.PyObject,N}) at /home/nhan/.julia/v0.5/PyCall/src/PyCall.jl:618
 in pycall(::PyCall.PyObject, ::Type{PyCall.PyAny}, ::PyCall.PyObject, ::Vararg{PyCall.PyObject,N}) at /home/nhan/.julia/v0.5/PyCall/src/PyCall.jl:618
 in #call#71(::Array{Any,1}, ::PyCall.PyObject, ::PyCall.PyObject, ::Vararg{PyCall.PyObject,N}) at /home/nhan/.julia/v0.5/PyCall/src/PyCall.jl:621
 in (::PyCall.PyObject)(::PyCall.PyObject, ::Vararg{PyCall.PyObject,N}) at /home/nhan/.julia/v0.5/PyCall/src/PyCall.jl:621
 in (::SymPy.SymFunction)(::SymEngine.Basic, ::SymEngine.Basic, ::Vararg{SymEngine.Basic,N}) at /home/nhan/.julia/v0.5/SymPy/src/call.jl:15
~~~~
Could you explain this error? Sorry I'm a newbie in both Python and Julia.

**Comment by isuruf** [comment]
@nhannguyen123, following should work if you are using the latest version. What version of SymEngine are you using?
```
using PyCall
using SymEngine
@vars x y
f = SymFunction("f")
@funs g h
```

**Comment by jverzani** [comment]
Oops, sorry for the noise @nhannguyen123 and @isuruf . I grepped through a stale version of SymEngine before answering.

**Comment by isuruf** [comment]
Ah, it seems you need SymEngine master for this. I'll make a release in a few hours.

> Oops, sorry for the noise @nhannguyen123 and @isuruf . I grepped through a stale version of SymEngine before answering.

np

**Comment by nhannguyen123** [comment]
@isuruf The versions that I'm using are
PyCall  | 1.14.0
----------|---------
SymEngine | 0.2.0
SymPy | 0.5.3
As I have said, after using SymPy I can defined *f, g, h* as follows
```Julia
using PyCall
using SymPy
@vars x y
f = SymFunction("f")
@symfuns g h # note that: @funs --> error
```
However the following code makes error
```Julia 
f(x,y)
```
If it's because the module I'm using is not the latest, then I will wait for the new release. Thanks.

**Comment by isuruf** [comment]
`SymPy` and `SymEngine` can't interoperate. So you should use either `SymPy` or `SymEngine`, not both.

For me, following works. If it doesn't please open an issue at https://github.com/JuliaPy/SymPy.jl
```julia
using PyCall
using SymPy
@vars x y
f = SymFunction("f")
@symfuns g h 
f(x,y)
```

If you want to use SymEngine, you can do

    Pkg.checkout("SymEngine")
    Pkg.build("SymEngine")

to use the git master. After doing that, you can do,

```julia
using SymEngine
@vars x y
f = SymFunction("f")
@funs g h
f(x,y)
```

**Comment by nhannguyen123** [comment]
@isuruf @jverzani Thank you. `SymEngine` works now.
